# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JYQC_SWIFT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'DNSPageView'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  pod 'SnapKit'
  pod 'Result'
  pod 'ESTabBarController-swift'
  pod 'LTScrollView'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'FSPagerView'
  pod 'SwiftMessages'
  # Pods for JYQC_SWIFT

  target 'JYQC_SWIFTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JYQC_SWIFTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
